version: '3.0'
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: sri8008/mysql:v1
    volumes:
    - mysql:/var/lib/mysql
    container_name: mysql
  backend:
    image: sri8008/backend:v1
    container_name: backend
    depends_on:
      - mysql
  web:
    image: sri8008/web:v1
    container_name: web
    depends_on:
      - backend
    ports:
      - 80:80
  